[package]
name = "raex"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[workspace]
members = [
	"components/raft",
	"components/dstore"
	]

[dependencies]
config = "0.11"
serde = { version = "^1.0.8", features = ["derive"] }
dstore = { path = "components/dstore" } 
raft = { path = "components/raft" }
tokio = { version = "0.2", features = ["macros", "sync", "stream", "time"] }
tokio-test = "0.2"
bytes = "1"
lazy_static = "*"
async-trait = "0.1"
tonic = "0.3"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3.0"
